--- 
knit: "bookdown::render_book"
title: "R for Environmental Chemists"
author: "David Hall, Steven Kutarna, Kristen Yeh, Hui Peng and Jessica D'eon"
date: "Last built on: `r Sys.Date()`"
url: 'https://davidrosshall.github.io/R4EnvChem/'
site: bookdown::bookdown_site
description: "This is a proof-of-concept for a further full length textbook."
documentclass: book
always_allow_html: true
bibliography: references.bib

---

# Preface {-}

Howdy, 
  
This website is more-or-less the living results of a collaborative project between us. We're not trying to be an exhaustive resource for all environmental chemists. Rather, we're focusing on developing broadly applicable data science course content (tutorials and recipes) based in `R`, specifically targeted towards undergraduate environmental chemistry courses and research. Please note that some of the later chapters are still a work in progress. 

This book is broken up into four sections: 

  - **Section 1: Getting Started in R** is a general guide for the complete novice that will help you install, setup, and run R code. It features a useful tutorial exercise to make sure you have a working script before starting courses. 
  - **Section 2: Data Analysis in R** introduces data analysis workflows and showcases *how* you can use R and the `tidyverse` to tackle the vast majority of the data science/analysis problems you'll encounter in undergraduate environmental chemistry courses. 
  - **Section 3: Data Analysis Toolbox** explores the theory behind the most common data analysis practices in environmental chemistry. These include linear regression analysis, plotting, etc. 
  - **Section 4: Notes for Env. Chem. Labs** consist of chapters specific to individual laboratory experiments. They rely upon knowledge from the previous three sections to introduce concepts unique to individual labs. 

We strongly recommend that you read through the Sections 1 and 2 in sequential order to understand the general R workflow which will be employed in all environmental chemistry courses. Once you're more confident in R and the `tidyverse`, you can check out any chapter in Section 3 for more detail on specific topics.

## Providing Feedback {-}

If you notice an error/mistake or have suggestions for adding features or improving the book, please reach out to any of the authors below or flag an issue on this books github repository at [https://github.com/DavidRossHall/R4EnvChem](https://github.com/DavidRossHall/R4EnvChem)

## Authors {-}
  
  If you have any questions/comments/suggestions/concerns please email:
  
  - [Dave](https://sites.chem.utoronto.ca/penglab/content/people) at [davidross.hall@mail.utoronto.ca](davidross.hall@mail.utoronto.ca)
  - [Steven](https://sites.chem.utoronto.ca/penglab/content/people) at [steven.kutarna@mail.utoronto.ca](steven.kutarna@mail.utoronto.ca)
  - [Kristen](https://www.abbattgroup.ca/members/) at [kristen.yeh@mail.utoronto.ca](kristen.yeh@mail.utoronto.ca)
  - [Professor D'eon](https://www.chemistry.utoronto.ca/people/directories/all-faculty/jessica-deon) at [jessica.deon@utoronto.ca](jessica.deon@utoronto.ca)
  

  